require:
  - rubocop-performance
  - rubocop-rake

inherit_mode:
  merge:
    - Exclude

AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: true
  TargetRubyVersion: 3.3
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"

# 以下に個別の設定を記述する
Layout/LineLength:
  Max: 140

Metrics/BlockLength:
  Max: 30
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Max: 35

Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/RedundantInitialize:
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
